lane :test do
  android_get_version_name(
    version_properties_file: "version.properties" # optional
  )

  #android_set_version_name(
  #  version_name: "1.23.4",
  #  version_properties_file: "app/build.gradle" # optional
  #)

  #android_get_version_code(
  #  version_properties_file: "app/build.gradle" # optional
  #)

  #android_set_version_code(
  #  version_code: 17, # optional, if not specified, Version Code will be incremented
  #  version_properties_file: "app/build.gradle" # optional
  #)
end
